{% set name = "pykube-ng" %}
{% set version = "22.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d59564485eea86677c695cc0724b4998bc5ff0b69e37d21fa8bf36379b683ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - google-auth
    - jsonpath-ng
    - pyyaml
    - requests >=2.12
    - requests-oauthlib

test:
  imports:
    - pykube
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://codeberg.org/hjacobs/pykube-ng
  summary: Lightweight Python 3+ client library for Kubernetes (pykube-ng)
  description: |
    Pykube (pykube-ng) is a lightweight Python 3.6+ client library for Kubernetes.

  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://pykube.readthedocs.io/en/latest/
  dev_url: https://codeberg.org/hjacobs/pykube-ng

extra:
  recipe-maintainers:
    - jacobtomlinson
